name: Build & Test CI
concurrency: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - run: pnpm run build

      - run: pnpm run lint

      - run: pnpm test
